[[MuesliMaterials]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "940217055e1a5ed85ae8602570bea7ed2856b4a8"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "943fa8c28fdbc8b61bb8123d8c9cb952f662ee2ada6217746eb9ca6523ec7fc6"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.0+0/MuesliMaterials.v1.16.0.aarch64-linux-musl-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11ee3dda58c4bc917a5ce525dae2db9517829601"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "a0cca6227545125ae16ff760d188bf6990b08f72e07328276de18c2e4773ace6"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.0+0/MuesliMaterials.v1.16.0.aarch64-linux-musl-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f266c3e422ac10c0923e36cae0a492d060ba5743"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "a4d947500eb9a93d9af3ad4d1e273c8dd19ea65aa4a05e971e47ad1e891d17e8"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.0+0/MuesliMaterials.v1.16.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93036077e14db79b67f2041a61e5fb62888d0977"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "698025fe6e9b5d31759c465569a4e31be8ef74c7db772099648603c7b12cb9e8"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.0+0/MuesliMaterials.v1.16.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7dd6cfc313c80779c1961784cfee2155741a36ad"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "bd77e2eb8ba638aa94dc3f72c2b4c9bfb0131298693d0aac788f4f8e0ba85b15"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.0+0/MuesliMaterials.v1.16.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ca0bf2b3745544bc26de18ac690805d8e947217"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "e6852d0286a749da443e947dbec6f3e2b072366ef3d0ffe6ccbcd8d00142036c"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.0+0/MuesliMaterials.v1.16.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2549fbf35cbac40e51cb810a615ddd33b0360ccf"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "6ed5ea22ae21e3fa0987027d0f34c70e850d94bd26a3064d04241db0ffb517d6"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.0+0/MuesliMaterials.v1.16.0.i686-linux-musl-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f792d33820c476154d1d110fef5c918444ae0b4"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "0a1e537f9b23fa309131feee0cf529a627e6a0431a1ffa8b32aa452f512a4e4f"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.0+0/MuesliMaterials.v1.16.0.i686-linux-musl-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "430192bf9c47bffd57d83b0e54a0e32d91dd8e0f"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "effa0871f4409c7e5c7ed0a59430507825a1340d5758777cccfb64cab99a9b2d"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.0+0/MuesliMaterials.v1.16.0.x86_64-linux-musl-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7a1a462aadf0f9e23e10f56eda9ff3fb03df026"
libc = "musl"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "011e2cddc06ef3336f248f6ffa63d6b18978ea127c93a485bf78633526e63526"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.0+0/MuesliMaterials.v1.16.0.x86_64-linux-musl-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
git-tree-sha1 = "53e7df8fc5a9268542fcc508b52aefbbd55f57b6"
os = "macos"

    [[MuesliMaterials.download]]
    sha256 = "eb568db5d8b9b57992e6ea14858d04bfc92d3b70798f808c438faa6a577ab6c3"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.aarch64-apple-darwin.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6efb3eddc8634880d253dd4386f7be88f410f93b"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "042ce128fb3f59ed15e926db0fb090593c16aee9720b106c4a0ba4430429fab7"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.aarch64-linux-gnu-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2507b2cfc4cdcd5dbd0f04726e60f7efe3d0b6c"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "fecb22afde1fe2c5f894c5446271ae16756fc4a21bc20454a5a9c91e58d2ff5d"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.aarch64-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "aarch64"
git-tree-sha1 = "117ad82126ca8b9672b728a2108ea865813d278b"
os = "freebsd"

    [[MuesliMaterials.download]]
    sha256 = "fbd587a6ecc43b8b5760c2b9ed739e3b828f281bca6064bad81dc048853e098c"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.aarch64-unknown-freebsd.tar.gz"
[[MuesliMaterials]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35126e8951ca70b7d324c5c5d943a0ac385ea3b3"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "4d2cc88222b20266e56e5446e33aa768d291f825cf91ee50edbab8979da75aa6"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14410468ade0144436ab17b62c3ea39c3e8167e0"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "9b401dbe81dc6ac603bff47e3dfac20e77165c14c7f4bd47525d5b55c0ba038f"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a32ad4b4006973107ba2d38c6e96f63ffd644a0"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "38ec14108227793cefc279e48275566724a8f392c3cd27206a60d39645a3271a"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5975d0be3aa91a6f51136e21bd1fd41a3bcb57a3"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "1d79fc8e8b597c598b24c38d9ceae573a34b9618753ff41a2880f55d16598330"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbfac42bad86ee43a139f3597a27322bd825a47d"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "b1ad0ae9d6b51916fd0d6189c938c8cb120ee0b54e740e9f0b14dbd0f646019b"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.i686-linux-gnu-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7255445b9d7bcb7f28b305715c70cd75e4fe0e58"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "e28abe1eb574d68ce6ea9cc8a1567a4127e1e4dbe6103dfbf1bf8c04619809d4"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.i686-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cfddbc42759837bccfdbd0535632a2a5945b27e"
os = "windows"

    [[MuesliMaterials.download]]
    sha256 = "c806e4bd7e36c75bff62d6e6d43786f16d040e07c30ca0e59e677320bcdfd550"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.i686-w64-mingw32-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fdef3067781a13e04cf2d51c49d6cea5b5ead8f"
os = "windows"

    [[MuesliMaterials.download]]
    sha256 = "2b0f5358c2d9c289d82d180fe46ea9485f70d0aef0c8179255eae112bda4db18"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.i686-w64-mingw32-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47b064af0d2367a03c325bcad02325eda0276307"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "403418d45ea624c39e62f7bf392e3c48b5794e6fff0a1cac87ab5e2007395c6a"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b890a31b6dbbd61707e6d507972039961219a6a6"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "1cff2f675d78779440431aa5f4973569e11cab59fb6773e23e625590a1a82999"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "674c5ac41013ab51f14d52088938f8905bac5b85"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "4c3430ae377f0b4bfc5e43f3bd82da3839c587e616153d0a6415dc797fdd93f6"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.riscv64-linux-gnu-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c819c07e423e420b0f864730cbef384d1e140c62"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "72374d17b80598e80336cb3a984145818df18f31d907f00e3f3f7e506564141d"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.riscv64-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
git-tree-sha1 = "a932d3d5cbdb26e1cf955c3979ee7717bbfd0335"
os = "macos"

    [[MuesliMaterials.download]]
    sha256 = "0a2fcfa908eccec3a8559dae2190ef47b7a0921d5bb1753cbb2cca4609cc02c7"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-apple-darwin.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8feee4e7c4868d60b9e61797f0eb855353dc070e"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "ac355b17ff580aecfb701dd6696bfbd6f5cf1e8ad474e87f58340409f5159926"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-linux-gnu-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7bb15e59ee26be291470f7c1ee1ab59f7665938"
libc = "glibc"
os = "linux"

    [[MuesliMaterials.download]]
    sha256 = "2bb48470220c0c35c56e76b66cddf15ee85680df9ea2dc1c74b2dee2e955aaf9"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-linux-gnu-cxx11.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
git-tree-sha1 = "0110c750d87eaceb8ff9d3388de2026583addf4d"
os = "freebsd"

    [[MuesliMaterials.download]]
    sha256 = "e627d2fd7bed60c6b163cad109cd07a25c29c49fae8e112ba5bc85eb481927c7"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-unknown-freebsd.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f5eb83575429d792e60a5c36b73b49710cbf649"
os = "windows"

    [[MuesliMaterials.download]]
    sha256 = "56996e28b6b0138fcb8a728e23bda521265b3b22f6a09a3770b31d7113970630"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[MuesliMaterials]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "598fd6a7e5c95c8cb6894ab2afd38a757624d2a4"
os = "windows"

    [[MuesliMaterials.download]]
    sha256 = "311aee37c2fb3d89b8088c737a3bcfccfda19592cf9a5f56a2bcf86fc86fe68d"
    url = "https://github.com/henrij22/MuesliMaterials_jll.jl/releases/download/MuesliMaterials-v1.16.3+0/MuesliMaterials.v1.16.3.x86_64-w64-mingw32-cxx11.tar.gz"
