# Autogenerated wrapper script for MuesliMaterials_jll for x86_64-apple-darwin
export libmuesli

using OpenBLAS32_jll
using LAPACK_jll
JLLWrappers.@generate_wrapper_header("MuesliMaterials")
JLLWrappers.@declare_library_product(libmuesli, "@rpath/libmuesli.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, LAPACK_jll)
    JLLWrappers.@init_library_product(
        libmuesli,
        "lib/libmuesli.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
